### ISSUE TITLE
[ETC] PCA Table에서 2개 이상의 PCA Column을 골라야 하는 사실을 알릴 필요가 있을 것 같습니다.

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/soroban#10]
PCA Table에서 2개 이상의 PCA Column을 골라야 하는 사실을 알릴 필요가 있을 것 같습니다.

현재 하나만 고르면 에러가 발생합니다. 두개 이상 골라라고만 기재되면 문제 없어 보입니다.

**Comment by jhk0530** [comment]
<img width="1310" alt="스크린샷 2023-10-02 오후 5 16 37" src="https://github.com/statgarten/soroban/assets/6457691/1bc984b5-e41f-4d86-bf4e-06eccbace539">
